name: funds-allocation
services:
  dev:
    image: 284409997699.dkr.ecr.us-east-1.amazonaws.com/funds-allocation
    build:
      context: ./
      dockerfile: ./Dockerfile/Dockerfile
    volumes:
      - type: volume
        source: funds-allocation
        target: /root/workspaces/funds-allocation
    tty: true
volumes:
  funds-allocation:
    driver: rclone
    driver_opts:
      remote: "onedrive:workspaces/funds-allocation"
